import type { Email, Label, Folder } from './types'

export const AVATAR_PALETTES: [string, string][] = [
  ['#F2A48F', '#D87856'],
  ['#9FC4EB', '#5E8FB8'],
  ['#C8B8E4', '#8A78B0'],
  ['#B8D8B0', '#7AA078'],
  ['#E8C798', '#C09858'],
  ['#E8A8B8', '#B86A82'],
  ['#9EC8C8', '#5E9090'],
  ['#D8B8D8', '#A878A8'],
]

export function colorForName(name: string): [string, string] {
  let h = 0
  for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) | 0
  return AVATAR_PALETTES[Math.abs(h) % AVATAR_PALETTES.length]
}

export function initials(name: string): string {
  const parts = name.split(/\s+/).filter(Boolean)
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase()
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase()
}

export const LABELS: Record<string, Label> = {
  work:     { name: 'Work',     color: '#5E8FB8' },
  personal: { name: 'Personal', color: '#E8B89A' },
  travel:   { name: 'Travel',   color: '#A8C0A4' },
  finance:  { name: 'Finance',  color: '#B8A8C8' },
  reading:  { name: 'Reading',  color: '#D89AAA' },
  shopping: { name: 'Shopping', color: '#E8D49A' },
}

export const FOLDERS: Folder[] = [
  { id: 'inbox',   name: 'Inbox',   icon: 'inbox',   count: 8 },
  { id: 'starred', name: 'Starred', icon: 'star',    count: 3 },
  { id: 'snoozed', name: 'Snoozed', icon: 'moon',    count: 2 },
  { id: 'sent',    name: 'Sent',    icon: 'send',    count: null },
  { id: 'drafts',  name: 'Drafts',  icon: 'edit',    count: 1 },
  { id: 'archive', name: 'Archive', icon: 'archive', count: null },
  { id: 'spam',    name: 'Spam',    icon: 'shield',  count: null },
  { id: 'trash',   name: 'Trash',   icon: 'trash',   count: null },
]

export const EMAILS: Email[] = [
  {
    id: 'e1',
    from: 'Maya Okafor',
    fromEmail: 'maya@northwindstudio.co',
    subject: 'Re: Friday review — moodboards are ready',
    preview: 'I added the third direction we talked about on Tuesday. Honestly, I think it might be my favourite — leaning into the warmer palette and—',
    body: [
      "Hey! Hope your week is going gently.",
      "Quick update on the Friday review: I've finished the moodboards and added a third direction we talked about on Tuesday. Honestly, I think it might be my favourite — it leans into the warmer palette and feels much closer to where the founders wanted to land.",
      "A few things I'd love your eyes on before we share with the wider team:",
      "  • The display type pairing on direction C — does it feel too editorial?\n  • Tone of the launch copy on slide 9 (I've taken a swing at it)\n  • Whether direction A is too close to what they have now",
      "I've attached the deck plus a couple of reference shots. Let me know if Friday at 10:30 still works — happy to push if you need more time.",
    ],
    sig: 'Maya\nDesign Lead, Northwind Studio',
    time: '9:42',
    date: 'today',
    unread: true,
    starred: true,
    labels: ['work'],
    folder: 'inbox',
    attachments: [
      { name: 'Friday-review-v4.pdf', size: '2.4 MB', kind: 'pdf', color: '#D87856' },
      { name: 'reference-shots.zip', size: '18 MB', kind: 'zip', color: '#8A78B0' },
    ],
    summary: 'Maya finished the Friday review moodboards and added a 3rd direction. She wants your feedback on the display type pairing, launch copy on slide 9, and whether direction A is too similar to the existing brand.',
    quickReplies: ["Looks great — let's ship", 'Can we push to next week?', 'Will review tonight'],
  },
  {
    id: 'e2',
    from: 'Headspace',
    fromEmail: 'hello@headspace.com',
    subject: 'Your weekly mindfulness recap, Alex',
    preview: 'You meditated 4 days this week — a small win worth celebrating. Here is a look at your patterns and a gentle suggestion for next week.',
    body: [
      "Hi Alex,",
      "You meditated 4 days this week — a small win worth celebrating. Most of those sessions happened in the morning, which seems to be when you feel most consistent.",
      "Your most-played session: 'Letting Go of Tension' (3 plays).",
      "A gentle suggestion: try a 5-minute wind-down before bed twice this week. Short sessions stick.",
    ],
    sig: 'Take care,\nThe Headspace team',
    time: '8:15',
    date: 'today',
    unread: true,
    starred: false,
    labels: ['personal'],
    folder: 'inbox',
    attachments: [],
    summary: 'Weekly mindfulness recap: 4 sessions this week, mostly mornings. Top session was "Letting Go of Tension". They suggest trying short wind-down sessions before bed.',
    quickReplies: [],
  },
  {
    id: 'e3',
    from: 'Theo Lindqvist',
    fromEmail: 'theo@brewstack.com',
    subject: 'coffee tomorrow? ☕',
    preview: "I'm in your neighbourhood for a thing at 11 — any chance you're around for a quick cup after? No pressure if not, we'll catch up properly soon.",
    body: [
      "Hey hey,",
      "I'm in your neighbourhood for a thing at 11 — any chance you're around for a quick cup after? No pressure if not, we'll catch up properly soon.",
      "There's that new place by the canal everyone keeps talking about. Could be a good excuse.",
    ],
    sig: 'T',
    time: '7:58',
    date: 'today',
    unread: true,
    starred: false,
    labels: ['personal'],
    folder: 'inbox',
    attachments: [],
    summary: "Theo is in your neighbourhood tomorrow at 11. Wants to grab coffee at the new place by the canal after.",
    quickReplies: ['Yes, see you there!', "Can't make it tomorrow", 'How about Thursday?'],
  },
  {
    id: 'e4',
    from: 'Linear',
    fromEmail: 'no-reply@linear.app',
    subject: '3 issues assigned to you this week',
    preview: 'A quick summary of what is on your plate: CM-204 (in progress), CM-211 (todo, due Thursday), and CM-218 (backlog, no due date).',
    body: [
      "Here's what's on your plate this week:",
      "  • CM-204 — Compose drawer auto-save (in progress)\n  • CM-211 — Search keyboard nav (todo, due Thursday)\n  • CM-218 — Sidebar collapse animation (backlog)",
      "View all in Linear →",
    ],
    sig: '',
    time: 'Yesterday',
    date: 'yesterday',
    unread: false,
    starred: false,
    labels: ['work'],
    folder: 'inbox',
    attachments: [],
    summary: '3 Linear issues assigned: CM-204 in progress, CM-211 due Thursday, CM-218 in backlog.',
    quickReplies: [],
  },
  {
    id: 'e5',
    from: 'Aer Lingus',
    fromEmail: 'booking@aerlingus.com',
    subject: 'Your trip to Lisbon — check-in opens in 24 hours',
    preview: 'Online check-in for flight EI484 (Dublin → Lisbon, Sat 18 May) opens at 14:25 tomorrow. Seat selection, baggage, and your boarding pass will be here.',
    body: [
      "Hi Alex,",
      "Your online check-in opens in 24 hours.",
      "  Flight: EI484\n  Dublin (DUB) → Lisbon (LIS)\n  Saturday 18 May, departs 14:25",
      "You'll be able to choose your seat, add baggage, and download your boarding pass.",
    ],
    sig: 'Safe travels,\nAer Lingus',
    time: 'Yesterday',
    date: 'yesterday',
    unread: false,
    starred: true,
    labels: ['travel'],
    folder: 'inbox',
    attachments: [
      { name: 'booking-EI484.pdf', size: '184 KB', kind: 'pdf', color: '#5E8FB8' },
    ],
    summary: 'Online check-in for your Dublin → Lisbon flight (EI484, Sat 18 May, 14:25) opens in 24 hours.',
    quickReplies: [],
  },
  {
    id: 'e6',
    from: 'Substack — Anna Wu',
    fromEmail: 'anna@substack.com',
    subject: 'The case for slow tools',
    preview: "I've been thinking about why some of the software I love most is the slowest. Not unresponsive — just unhurried. There is a difference.",
    body: [
      "I've been thinking about why some of the software I love most is the slowest. Not unresponsive — just unhurried. There is a difference.",
      "The best slow tools refuse to fragment your attention. They have one job, they do it well, and they leave you alone the rest of the time...",
      "(Continue reading on Substack)",
    ],
    sig: '— Anna',
    time: 'Mon',
    date: 'this week',
    unread: false,
    starred: false,
    labels: ['reading'],
    folder: 'inbox',
    attachments: [],
    summary: 'Anna Wu newsletter: a reflection on why some of the best software is intentionally unhurried, refusing to fragment attention.',
    quickReplies: [],
  },
  {
    id: 'e7',
    from: 'Stripe',
    fromEmail: 'receipts@stripe.com',
    subject: 'Receipt from Figma — €18.00',
    preview: 'Your monthly Figma subscription was charged to Visa •• 4421. View receipt, manage subscription, or contact support if anything looks off.',
    body: [
      "Receipt from Figma",
      "Amount: €18.00\nDate: 12 May 2026\nCard: Visa ending 4421",
      "View receipt →",
    ],
    sig: '',
    time: 'Mon',
    date: 'this week',
    unread: false,
    starred: false,
    labels: ['finance'],
    folder: 'inbox',
    attachments: [],
    summary: 'Monthly Figma subscription charged €18.00 to Visa ••4421.',
    quickReplies: [],
  },
  {
    id: 'e8',
    from: 'Sara Beltrán',
    fromEmail: 'sara.b@northwindstudio.co',
    subject: 'Notes from the brand sync',
    preview: 'Quick recap from this morning. The founders are leaning toward direction B but want to see what C could look like with the warmer palette before deciding.',
    body: [
      "Sharing my notes from the brand sync this morning while it's all fresh.",
      "  • Founders leaning toward direction B\n  • Want to see C with the warmer palette before deciding\n  • Logo size on smaller surfaces is a concern\n  • Next review: Thursday 11:00",
      "Let me know if I missed anything — I'll send the deck around tomorrow.",
    ],
    sig: 'Sara',
    time: 'Sun',
    date: 'this week',
    unread: false,
    starred: false,
    labels: ['work'],
    folder: 'inbox',
    attachments: [],
    summary: "Sara's notes from the brand sync: founders leaning direction B, want to see C with warmer palette, concern about logo at small sizes. Next review Thursday 11:00.",
    quickReplies: [],
  },
  {
    id: 'e9',
    from: 'Notion',
    fromEmail: 'team@notion.so',
    subject: "What's new in Notion — Calendar, AI Q&A, and more",
    preview: "We're rolling out a redesigned calendar view, smarter AI Q&A across your entire workspace, and a handful of small refinements you'll feel right away.",
    body: ["Lots of small refinements this month — full changelog inside."],
    sig: '',
    time: '9 May',
    date: 'this week',
    unread: false,
    starred: false,
    labels: ['reading'],
    folder: 'inbox',
    attachments: [],
    summary: 'Notion product update: new calendar view, smarter AI Q&A across workspaces, plus small refinements.',
    quickReplies: [],
  },
  {
    id: 'e10',
    from: 'Mum',
    fromEmail: 'eleanor.h@gmail.com',
    subject: 'photos from the weekend 🌷',
    preview: "Finally got around to sending these. The garden is in full bloom — your dad insists you have not seen it like this. Hope you are eating well!",
    body: [
      "Finally got around to sending these. The garden is in full bloom — your dad hasn't seen it like this. Hope you're eating well!",
      "Call when you can, no rush.",
    ],
    sig: 'Love,\nMum xx',
    time: '7 May',
    date: 'this week',
    unread: false,
    starred: true,
    labels: ['personal'],
    folder: 'inbox',
    attachments: [
      { name: 'garden-may.zip', size: '46 MB', kind: 'zip', color: '#7AA078' },
    ],
    summary: 'Mum sent garden photos from the weekend. Wants you to call when you can.',
    quickReplies: ['Calling tonight ❤️', 'These are beautiful', 'Thanks Mum, will call this weekend'],
  },
  {
    id: 'e11',
    from: 'Brewstack Weekly',
    fromEmail: 'newsletter@brewstack.com',
    subject: 'Issue 142 — the slow web, again',
    preview: '12 links worth your time this week, plus a long read on why minimal feeds are quietly making a comeback. Reading time: ~8 minutes.',
    body: ["12 links worth your time this week, plus a long read on minimal feeds."],
    sig: '',
    time: '5 May',
    date: 'earlier',
    unread: false,
    starred: false,
    labels: ['reading'],
    folder: 'inbox',
    attachments: [],
    summary: 'Brewstack Weekly issue 142: 12 curated links and a long read about minimal feeds making a comeback. 8 min read.',
    quickReplies: [],
  },
  {
    id: 'e12',
    from: 'Revolut',
    fromEmail: 'no-reply@revolut.com',
    subject: 'Your April spending recap',
    preview: 'You spent €1,842 in April across 47 transactions. Top category: Groceries (€312). You stayed under budget in 4 of 6 categories — nice work.',
    body: ["Your April spending recap is ready in the app."],
    sig: '',
    time: '3 May',
    date: 'earlier',
    unread: false,
    starred: false,
    labels: ['finance'],
    folder: 'inbox',
    attachments: [],
    summary: 'April spending: €1,842 across 47 transactions. Top category Groceries (€312). Under budget in 4/6 categories.',
    quickReplies: [],
  },
]
